import { currency } from "./interfaces";

export const currencies: currency[] = [
    {
        id: 1,
        name: "United States Dollar",
        symbol: "$",
        flag: "🇺🇸",
        conversion: 1.0,
    },
    {
        id: 2,
        name: "Euro",
        symbol: "€",
        flag: "🇪🇺",
        conversion: 0.89,
    },
    {
        id: 3,
        name: "British Pound",
        symbol: "£",
        flag: "🇬🇧",
        conversion: 0.76,
    },
    {
        id: 4,
        name: "Japanese Yen",
        symbol: "¥",
        flag: "🇯🇵",
        conversion: 133.33,
    },
    {
        id: 5,
        name: "Chinese Yuan",
        symbol: "¥",
        flag: "🇨🇳",
        conversion: 6.5,
    },
    {
        id: 6,
        name: "Indian Rupee",
        symbol: "₹",
        flag: "🇮🇳",
        conversion: 63.63,
    },
    {
        id: 7,
        name: "Russian Ruble",
        symbol: "₽",
        flag: "🇷🇺",
        conversion: 65.65,
    },
    {
        id: 8,
        name: "Canadian Dollar",
        symbol: "$",
        flag: "🇨🇦",
        conversion: 1.34,
    },
    {
        id: 9,
        name: "Australian Dollar",
        symbol: "$",
        flag: "🇦🇺",
        conversion: 1.35,
    },
    {
        id: 10,
        name: "New Zealand Dollar",
        symbol: "$",
        flag: "🇳🇿",
        conversion: 1.42,
    },
    {
        id: 11,
        name: "Singapore Dollar",
        symbol: "$",
        flag: "🇸🇬",
        conversion: 1.49,
    },
    {
        id: 12,
        name: "Hong Kong Dollar",
        symbol: "$",
        flag: "🇭🇰",
        conversion: 7.75,
    },
    {
        id: 13,
        name: "South Korean Won",
        symbol: "₩",
        flag: "🇰🇷",
        conversion: 110.0,
    },
    {
        id: 14,
        name: "South African Rand",
        symbol: "R",
        flag: "🇿🇦",
        conversion: 2.52,
    },
    {
        id: 15,
        name: "Danish Krone",
        symbol: "kr",
        flag: "🇩🇰",
        conversion: 6.55,
    },
    {
        id: 16,
        name: "Swedish Krona",
        symbol: "kr",
        flag: "🇸🇪",
        conversion: 9.05,
    },
    {
        id: 17,
        name: "Norwegian Krone",
        symbol: "kr",
        flag: "🇳🇴",
        conversion: 10.75,
    },
    {
        id: 18,
        name: "Finnish Markka",
        symbol: "€",
        flag: "🇫🇮",
        conversion: 12.5,
    },
    {
        id: 19,
        name: "Polish Zloty",
        symbol: "zł",
        flag: "🇵🇱",
        conversion: 33.33,
    },
    {
        id: 20,
        name: "Czech Koruna",
        symbol: "Kč",
        flag: "🇨🇿",
        conversion: 21.05,
    },
    {
        id: 21,
        name: "Hungarian Forint",
        symbol: "Ft",
        flag: "🇭🇺",
        conversion: 27.55,
    },
    {
        id: 22,
        name: "Romanian Leu",
        symbol: "lei",
        flag: "🇷🇴",
        conversion: 43.48,
    },
    {
        id: 23,
        name: "Bulgarian Lev",
        symbol: "lev",
        flag: "🇧🇬",
        conversion: 43.48,
    },
]